### ISSUE TITLE
cmd+{ causes browser to go "back" and lose all changes

### ISSUE THREAD

**Issue by colllin** [rissem/meteorpad#18]

**Comment by rissem** [comment]
Hey @colllin, hope you didn't lose a lot of work because of that. You'll see the same behavior if you press the back button as well. Did you try pressing forward? That should work, but I wouldn't rely on that behavior.

If you were logged in, your work should be saved under your pad listing (underneath your account).

I don't think this is a bug, but if you have any ideas for making this experience better, I'm all ears.

**Comment by colllin** [comment]
Yeah, I have an idea.

Put a confirm dialog on unload to help people avoid losing work.
