### ISSUE TITLE
MeteorPad is down - what about support to community

### ISSUE THREAD

**Issue by TomFreudenberg** [rissem/meteorpad#44]
Hi Michael (@rissem)

I do not want to discuss why you have closed the meteopad support - sure you have your reasons.

What I am struggling with is, the bad influence you make on using open / free (source) stuff. There were so many meteor examples and helping codes created inside a meteorpad - and now, you drop them all off. Looking to threads on StackExchange and on MeteorForum you will find a huge number of links to meteorpad - which means also to the source of know how. 

By now, you blow some part of the (meteor) internet just away. That can't be good. If I look to myself, I am shocked that I believed in a system and a community element that is just dropped now - no chance to access my personal written know how currently.

So my request and appeal to you at least is: make the sources available from the different meteor pads so that the links will end up in showing sources.

Thanks for some feedback
Tom

**Comment by bobsback** [comment]
agree

**Comment by TomFreudenberg** [comment]
Hi Michael ( @rissem )

no update - no feedback - no statement ?

Please show kindness behaviour - we still believed and supported sometimes your ideas.

Tom

**Comment by derwaldgeist** [comment]
+1

I just came here because I wanted to follow a link to meteorpad from the meteor forums. Funny enough, it happened to be one of @TomFreudenberg's posts.

@TomFreudenberg Do you happen to have a github repo that resembles this posting:
https://forums.meteor.com/t/meteor-and-the-internet-of-things-iot-whats-best-to-use-collection-meteor-streams-streamy/792/10

I'm trying to figure out how to setup a streaming scenario. I used to use Meteor.Streams, but as it is not supported anymore, I'm looking for an alternativ that also supports horizontal scaling.

**Comment by TomFreudenberg** [comment]
Hi Tom ( @derwaldgeist ) - sorry have no backup about that - I believed in meteorpad :-(

**Comment by derwaldgeist** [comment]
So did I...

BTW: I'm still looking for a scalable alternative for Meteor Streams, as it is not supported anymore. Streamy looks nice, but won't scale horizontally. Using a dedicated server like MQTT or REDIS is not really an option for me, since I would like to keep things as simple as possible. Did you find any alternative to Meteor Streams that is scalable?

**Comment by TomFreudenberg** [comment]
Hi Michael (@rissem )

as anybody can see from your profile, you are still active and - thanks god - still alive these days [e.g. commits on MedBook](https://github.com/UCSC-MedBook/MedBook-Documentation/commits?author=rissem).

I am really wondering why you haven't send any feedback since now. Isn't this something like a kindly deal with all the peoples respecting you and supporting your work and ideas? Don't you respect them or what is the problem to post an answer - even a short one?

I have not abandon the hope that you upload my and the other public sources (a dump from the meteorpad mongo) somewhere.

Looking for an answer
Tom

**Comment by rissem** [comment]
Please see my response on the Meteor forums

https://forums.meteor.com/t/what-happened-to-meteorpad-com/20029/2
